# Schema for the configuration files of the Po Translations Report module.

po_translations_report.admin_config:
  type: config_object
  label: 'Po Translations Report settings'
  mapping:
    folder_path:
      type: string
      label: 'Path to the directory with po files'
    display_method:
      type: string
      label: 'Display method'
    sortable_linked_data_table_configuration:
      type: mapping
      label: 'Configuration parameters for sortable_linked_data_table method'
    details_display_method:
      type: string
      label: 'Details display method'
    html_table_configuration:
      type: mapping
      label: 'Configuration parameters for html_table method'